version: "3.7"

services:
  database_zoonoses:
    image: postgres
    container_name: database_zoonoses
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=ignite
      - POSTGRES_DB=zoonoses
    volumes:
      - pgdata:/data/postgres
  app:  
    build: .
    container_name: zoonoses
    ports:
      - 3333:3333
      - 9229:9229
    volumes:
      - .:/usr/app
    links:
      - database_zoonoses
    depends_on:   
      - database_zoonoses

volumes:
  pgdata:
    driver: local